# -*- coding: utf-8 -*-
"""Code_Challenge_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znl6D58gMXKsW4NYxwy0TYnMYdoxjJtd
"""

pip install pillow

from PIL import Image, ImageDraw, ImageFont

#Our Inputted Image From Current Directory
input = Image.open('/content/Heist.jpg')
width, height = input.size

#Name With Which WaterMark Will Be Created
mark = ImageDraw.Draw(input)
text = "Money Heist"

#Default Font Of WaterMarked Text
font = ImageFont.load_default()
textwidth, textheight = draw.textsize(text, font)

#Setting Margins(X & Y Coordinates) For Text
margin = 10
x = width - textwidth - margin
y = height - textheight - margin

#Applying Watermark in the Bottom Right Corner As Present In Traditional Smartphone Cameras
draw.text((x, y), text, font=font)
input.show()

#Save The Required WaterMark Image Within Same Directory
input.save('/content/Heist_With_WaterMark.jpg')

